apiVersion: v1
kind: Service
metadata:
  name: {{ template "component.name" . }}
  namespace: {{ .Values.global.kubernetes.namespace }}
  labels:
    app: {{ template "component.name" . }}
    name: {{ template "component.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    app: {{ template "component.name" . }}
    name: {{ template "component.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
